from __future__ import division

import nn
import numpy as np
import random
import utils as u

from itertools import product
from sklearn.utils.extmath import cartesian
from tqdm import tqdm


class KFoldCrossValidation(object):
    """
    This class represents a wrapper for the implementation of the classic
    k-fold cross validation algorithm, as described in Deep Learning pag.
    120.

    Attributes
    ----------
    full_dataset: numpy.ndarray
        the full dataset obtained by stiking the design matrix X with the
        target column vector y

    folds: list
        a list containing nfold chunks of the original dataset

    results: list
        a list containing the generalization errors generated by every
        algorithm's iteration

    mean_results: float
        the mean generalization error

    neural_net: nn.NeuralNetwork
        the neural network that has to be cross validated
    """

    def __init__(self, X, y, neural_net, nfold=3, **kwargs):
        """
        The class' constructor.

        Parameters
        ----------
        X: numpy.ndarray
            the design matrix

        y: numpy.ndarray
            the target column vector

        nfold: int
            the number of folds to be applied in the algorithm
            (Default value = 3)

        kwargs: dict
            a dictionary which contains the parameters for the neural
            network's initialization

        Returns
        -------
        """
        assert X.shape[0] == y.shape[0]

        self.full_dataset = np.hstack((X, y.reshape(-1, 1)))
        self.folds = list()
        self.results = list()
        self.mean_results = 0.0

        np.random.shuffle(self.full_dataset)
        self.set_folds(nfold)

        # self.neural_net = nn.NeuralNetwork(X, y, kwargs['hidden_sizes'])

        self.validate(X, y, neural_net, nfold, eta=kwargs['eta'],
                      alpha=kwargs['alpha'], epochs=kwargs['epochs'],
                      batch_size=kwargs['batch_size'],
                      reg_lambda=kwargs['reg_lambda'],
                      reg_method=kwargs['reg_method'])

    def set_folds(self, nfold):
        """
        This function splits the dataset into nfold folds.

        Parameters
        ----------
        nfold: int
            the number of folds to be applied in the algorithm

        Returns
        -------
        """
        record_per_fold = int(self.full_dataset.shape[0] / nfold)
        low = 0
        high = low + record_per_fold

        for i in np.arange(nfold):
            self.folds.append(self.full_dataset[low:high] if i !=
                              nfold - 1 else self.full_dataset[low:])

            low = high
            high += record_per_fold

    def validate(self, X, y, neural_net, nfold, **kwargs):
        """
        This function implements the core of the k-fold cross validation
        algorithm. For each fold, the neural network is trained using the
        training set created for that fold, and is tested on the respective
        test set. Finally, the error between the test's target and the
        predicted one is collected.

        Parameters
        ----------
        X. numpy.ndarray
            the design matrix

        y: numpy.ndarray
            the target column vector

        nfold: int
            the number of folds to be applied in the algorithm

        kwargs: dict
            a dictionary which contains the parameters for the neural
            network's initialization

        Returns
        -------
        """
        for i in tqdm(np.arange(nfold),
                      desc='{}-FOLD CROSS VALIDATION PROGRESS'.format(nfold)):
            train_set_full = np.vstack([self.folds[j] for j in np.arange(
                len(self.folds)) if j != i])
            train_set = train_set_full[:, :-1]
            train_target = train_set_full[:, -1].reshape(-1, 1)
            test_set = self.folds[i][:, :-1]
            test_target = self.folds[i][:, -1].reshape(-1, 1)

            neural_net.train(train_set, train_target, kwargs['eta'],
                             kwargs['alpha'], kwargs['epochs'],
                             kwargs['batch_size'], kwargs['reg_lambda'],
                             kwargs['reg_method'])

            loss = neural_net.predict(test_set, test_target)
            self.results.append(loss)
            neural_net.reset()

        self.mean_result = np.mean(self.results)


class HyperRandomGrid():
    """ HyperRandomGrid """

    def __init__(self, param_ranges, N, seed=None):
        """
        HyperRandomGrid instanciates an iterator
        which produce random parameters, in the given ranges.

        The grid iterator is reset after each use,
        allowing immediate reuse of the same grid.

        Parameters
        ----------
        param_ranges : dict
        dictionary containing ranges interval for each parameter.

        N: int
        size of the grid.

        seed: int
        random seed initialization.

        Returns
        -------

        """

        self.N = N
        self.n = 0
        if type(param_ranges) is not dict:
            raise TypeError("Insert a dictionary of parameters ranges")
        self.param_ranges = param_ranges
        self.types = self.get_types()

        if seed is not None:
            # seed inizialization
            self.seed = seed
            random.seed(self.seed)
        else:
            # random initialization
            random.seed()
            self.seed = random.randint(0, 2**32)
            random.seed(self.seed)

    def get_types(self):
        """
        Get the type of each parameter

        Parameters
        ----------

        Returns
        -------
        types : dict
        dictionary containing each parameter type
        """

        types = dict()
        for par, interval in self.param_ranges.items():
            if type(interval[0]) is int and type(interval[1] is int):
                types[par] = int
            elif type(interval[0]) is float and type(interval[1] is float):
                types[par] = float
            else:
                raise TypeError('Check interval type')
        return types

    def __iter__(self):
        return self

    def next(self):
        """
        Iterator next method,
        returns the next grid record

        Parameters
        ----------
        Returns
        -------
        x_grid : dict
        Randomized parameter dictionary
        """
        if self.n == 0:
            random.seed(self.seed)

        x_grid = dict()
        for par, interval in self.param_ranges.items():
            if self.types[par] is int:
                x_grid[par] = random.randint(interval[0], interval[1])
            else:
                x_grid[par] = random.uniform(interval[0], interval[1])

        self.n += 1
        if self.n == self.N+1:
            self.n = 0
            # set random seed at exit
            random.seed()
            raise StopIteration
        else:
            return x_grid

    def reset_grid(self):
        """Reset the grid, to use again the iterator """
        random.seed(self.seed)
        self.n = 0

    def get_par_index(self, index):
        self.reset_grid()
        for i in range(index+1):
            params = self.next()
        return params


class HyperGrid():
    """
    HyperGrid class  instanciates a grid iterator object

    Attributes
    ----------
    grid_f: dict
        A dictionary containing function to generate parameters arrays
        using the input ranges

    """
    grid_f = {
        'linspace':
        {
            int: lambda start, end, num:
            np.linspace(start, end, num, dtype=int),
            float: lambda start, end, num:
            np.linspace(start, end, num, dtype=float)
        },
        'random':
        {
            int: lambda start, end, num:
            np.random.randint(start, end, num, dtype=int),
            float: lambda start, end, num:
            np.random.uniform(start, end, num)
        }
    }

    def __init__(self, param_ranges, size, method, ):
        """
        Initialize

        Parameters
        ----------
        param_ranges : dict
            dictionary containing hyperparameters ranges

        size : int
            size of each hyperparameter array

        method : str
            'linspace' to generate a uniform grid space
            'random' to generate a random grid

        Returns
        -------

        """

        self.param_ranges = param_ranges
        self.size = size
        self.method = method
        self.params = param_ranges.keys()
        self.params_index = {par: self.params.index(par)
                             for par in self.params}
        # set seed for the hyperGrid object
        self.seed = random.randint(0, 2**32)
        self.grid = self.get_grid()

        print('GENERATING AN HYPERPARAMETER GRID OF LENGTH {}'
              .format(self.get_grid_size()))

    def get_grid(self):
        """
        Produces the grid iterator

        Returns
        -------
        grid_iter: itertools.product
            a grid iterator
        """
        np.random.seed(seed=self.seed)
        par_vectors = dict()
        for par, interval in self.param_ranges.items():
            par_vectors[par] = self.grid_f[self.method][type(interval[0])](
                interval[0],
                interval[1],
                self.size
            )
            # return par_vectors
        grid_iter = product(*list(par_vectors.values()))
        return grid_iter

    def get_grid_list(self):
        """ get the grid as a list """
        grid_list = list(self.get_grid())

        return grid_list

    def get_grid_dict(self):
        """ get the grid as a dict """
        grid_iter = self.get_grid()
        grid_dict = {par: [] for par in self.params}
        for par_values in grid_iter:
            for par in self.params:
                grid_dict[par].append(
                    par_values[self.params_index[par]]
                )
        return grid_dict

    def get_grid_size(self):
        """ get the grid size """
        return self.size**len(self.params)

    def __iter__(self):
        """
        iterator method
        """
        return self

    def next(self):
        """
        Return next grid parameters as a dictionary
        """
        out = self.grid.next()

        d = dict()
        for i, par in enumerate(self.params):
            d[par] = out[i]

        return d

    def reset_grid(self):
        """
        Re-create the grid iterator, maintaining the same
        parameters
        """
        self.grid = self.get_grid()


class GridSearch(object):
    """
    This class is a wrapper for the grid search algorithm for the
    hyperparameters' optimization. It is possible to randomize the whole
    process by settig the random_search variable to True.

    Attributes
    ----------
    grid: numpy.ndarray
        A matrix in which each row represents a possible combination of
        hyperparameters that has to be tested

    results: dict
        A dictionary in which the keys are the mean error scores returned by
        the k-fold cross validation phase and the values are the
        hyperparameters that have produced that errors

    best_result: dict
        The best result returned by the search phase
    """

    def __init__(self, X, y, random_search=False, **kwargs):
        """
        The class' constructor.

        Parameters
        ----------
        X: numpy.ndarray
            the design matrix

        y: numpy.ndarray
            the target column vector

        random_search: bool
            whether or not to proceed with a random hyperparameters's
            initialization
            (Default value = False)

        kwargs: dict
            either the parameters' range if random_search is True or
            the parameters' records if random_search is False

        Returns
        -------
        """
        self.grid = self.set_grid(random_search, kwargs['par_ranges'] if
                                  random_search else kwargs['parameters'])
        self.results = self.search(X, y)
        self.best_result = {'error': min(self.results.keys()),
                            'parameters': self.results[min(
                                              self.results.keys())]}

    def set_grid(self, random_search, par_or_par_ranges, num_par=3):
        """
        This function initializes the algorithm's grid attribute.

        Parameters
        ----------
        random_search: bool
            whether or not to proceed with a random hyperparameters's
            initialization
            (Default value = False)

        par_or_par_ranges: dict
            a dictionary containing either the parameters' ranges if
            random_search is True or the parameters' records if random_search
            is False

        num_par: int
            the length of the parameters' records
            (Default value = 3)

        Returns
        -------
        The grid as a numpy.ndarray.
        """
        grid = None

        if random_search:
            grid = HyperRandomGrid(par_or_par_ranges, num_par)
            grid = u.from_dict_to_list(grid)
        else:
            grid = u.from_dict_to_list(par_or_par_ranges)

        grid = cartesian([grid['eta'], grid['alpha'], grid['reg_lambda'],
                          grid['batch_size'], grid['epochs']])

        return grid

    def search(self, X, y, **kwarg):
        """
        This functions implements the search phase of the grid search
        algorithm.

        Parameters
        ----------
        X: numpy.ndarray
            the design matrix

        y: numpy.ndarray
            the target column vector

        kwargs: dict

        Returns
        -------
        A dictionary in which the keys are the mean error scores returned by
        the k-fold cross validation phase and the values are the
        hyperparameters that have produced that errors.
        """
        neural_net = nn.NeuralNetwork(X, y)
        results = dict()

        for record in tqdm(self.grid, desc='GRID SEARCH PROGRESS'):
            cross_val = KFoldCrossValidation(
                X, y, neural_net, eta=record[0],
                alpha=record[1], reg_method='l2', reg_lambda=record[2],
                batch_size=int(record[3]), epochs=int(record[4]))

            results[cross_val.mean_results] = {'eta': record[0],
                                               'alpha': record[1],
                                               'reg_lambda': record[2],
                                               'batch_size': int(record[3]),
                                               'epochs': int(record[4])}

        return results
